/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '~/core/http'
import { Observable } from 'rxjs'
import { ApiDemandController } from '~/config/services/api-demand.controller'

export class ApiDemandService {
    /**
     * all
     */
    @Request({
        server: ApiDemandController.all
    })
    public all(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * create
     */
    @Request({
        server: ApiDemandController.create
    })
    public create(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
