/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '~/core/http'
import { Observable } from 'rxjs'
import { ApiController } from '~/config/services/api.controller'

export class ApiService {
    /**
     * all
     */
    @Request({
        server: ApiController.all
    })
    public all(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
