/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '~/core/http'
import { Observable } from 'rxjs'
import { AuthController } from '~/config/services/auth.controller'

export class AuthService {
    /**
     * login
     */
    @Request({
        server: AuthController.login
    })
    public login(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
