/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '~/core/http'
import { Observable } from 'rxjs'
import { DemandController } from '~/config/services/demand.controller'

export class DemandService {
    /**
     * create demand
     */
    @Request({
        server: DemandController.post
    })
    public post(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * update demand
     */
    @Request({
        server: DemandController.put
    })
    public put(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * apiName 模糊查询
     */
    @Request({
        server: DemandController.apiList
    })
    public apiList(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * check api submit
     */
    @Request({
        server: DemandController.getDetail
    })
    public getDetail(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
