/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '~/core/http'
import { Observable } from 'rxjs'
import { IwsGenerationController } from '~/config/services/iws-generation.controller'

export class IwsGenerationService {
    /**
     * generate IWS code
     */
    @Request({
        server: IwsGenerationController.post
    })
    public post(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
