/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '~/core/http'
import { Observable } from 'rxjs'
import { MuleApplicationCreationController } from '~/config/services/mule-application-creation.controller'

export class MuleApplicationCreationService {
    /**
     * generate RAML code
     */
    @Request({
        server: MuleApplicationCreationController.post
    })
    public post(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
