/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '~/core/http'

// 控制器名称
const controller = 'account'

export const AccountController = {
    // 修改账号角色
    role: {
        controller,
        action: 'role',
        type: RequestMethod.Put
    }
}
