/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '~/core/http'

// 控制器名称
const controller = 'account'

export const AccountController = {
    // all
    all: {
        controller,
        action: 'all',
        type: RequestMethod.Get
    },
    // 修改账号角色
    role: {
        controller,
        action: 'role',
        type: RequestMethod.Put
    },
    // getAccountInfoByStaffId
    userId: {
        controller,
        action: 'userId',
        type: RequestMethod.Get
    }
}
