/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '~/core/http'

// 控制器名称
const controller = 'api'

export const ApiController = {
    // all
    all: {
        controller,
        action: 'all',
        type: RequestMethod.Get
    }
}
