/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '~/core/http'

// 控制器名称
const controller = 'auth'

export const AuthController = {
    // login
    login: {
        controller,
        action: 'login',
        type: RequestMethod.Post
    }
}
