/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '~/core/http'

// 控制器名称
const controller = 'directory'

export const DirectoryController = {
    // 获取全部数据字典
    directories: {
        controller,
        action: 'directories',
        type: RequestMethod.Get
    },
    // 获取数据字典
    getDirectoryByType: {
        controller,
        action: 'getDirectoryByType',
        type: RequestMethod.Get
    }
}
