/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '~/core/http'

// 控制器名称
const controller = 'iws-generation'

export const IwsGenerationController = {
    // generate IWS code
    post: {
        controller,
        type: RequestMethod.Post
    }
}
