/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '~/core/http'

// 控制器名称
const controller = 'mule-application-creation'

export const MuleApplicationCreationController = {
    // generate RAML code
    post: {
        controller,
        type: RequestMethod.Post
    }
}
