/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '~/core/http'

// 控制器名称
const controller = 'mule-project-creation'

export const MuleProjectCreationController = {
    // generate Mule code
    post: {
        controller,
        type: RequestMethod.Post
    }
}
